# Generated by Django 2.2.19 on 2021-05-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bantuan_koperasi_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(max_length=200)),
                ('id_kub', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bantuan_koperasi_dak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaring', models.CharField(max_length=200)),
                ('kapal', models.CharField(max_length=200)),
                ('id_koperasi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bantuan_kub_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(max_length=200)),
                ('id_kub', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bantuan_kub_dak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaring', models.CharField(max_length=200)),
                ('fish_finder', models.CharField(max_length=200)),
                ('kapal', models.CharField(max_length=200)),
                ('id_kub', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='koperasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_koperasi', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('no_hp', models.CharField(max_length=100)),
                ('ketua', models.CharField(max_length=100)),
                ('jumlah_amggota', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='kub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kub', models.CharField(max_length=200)),
                ('no_regitrasi', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('nama_ketua', models.CharField(max_length=100)),
                ('jumlah_amggota', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kub_awal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelompok', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('id_kub', models.CharField(max_length=50)),
            ],
        ),
    ]
