# Generated by Django 2.2.19 on 2021-05-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kub',
            old_name='jumlah_amggota',
            new_name='jumlah_anggota',
        ),
    ]
