# Generated by Django 2.2.19 on 2021-05-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0003_auto_20210530_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koperasi',
            old_name='jumlah_amggota',
            new_name='jumlah_anggota',
        ),
    ]
