# Generated by Django 2.2.19 on 2021-05-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0004_auto_20210530_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='bantuan_koperasi_kkp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(blank=True, max_length=200, null=True)),
                ('id_kub', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bantuan_kub_kkp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(blank=True, max_length=200, null=True)),
                ('id_kub', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bantuan_koperasi_api',
        ),
        migrations.DeleteModel(
            name='bantuan_kub_api',
        ),
        migrations.AlterField(
            model_name='bantuan_koperasi_dak',
            name='id_koperasi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bantuan_koperasi_dak',
            name='jaring',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bantuan_koperasi_dak',
            name='kapal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bantuan_kub_dak',
            name='fish_finder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bantuan_kub_dak',
            name='id_kub',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bantuan_kub_dak',
            name='jaring',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bantuan_kub_dak',
            name='kapal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
