# Generated by Django 2.2.19 on 2021-05-31 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0005_auto_20210530_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bantuan_kub_dak',
        ),
        migrations.DeleteModel(
            name='bantuan_kub_kkp',
        ),
    ]
