# Generated by Django 2.2.19 on 2021-05-31 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0006_auto_20210531_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='bantuan_kub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaring', models.CharField(blank=True, max_length=200, null=True)),
                ('fish_finder', models.CharField(blank=True, max_length=200, null=True)),
                ('kapal', models.CharField(blank=True, max_length=200, null=True)),
                ('gn', models.CharField(blank=True, max_length=200, null=True)),
                ('jaring_insang', models.CharField(blank=True, max_length=200, null=True)),
                ('id_kub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siperkap.kub')),
            ],
        ),
    ]
