# Generated by Django 3.1.4 on 2021-05-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0007_bantuan_kub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bantuan_kub',
            name='id_kub',
        ),
    ]
