# Generated by Django 3.1.4 on 2021-05-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0009_bantuan_kub_kub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bantuan_koperasi_dak',
        ),
        migrations.DeleteModel(
            name='bantuan_koperasi_kkp',
        ),
    ]
