# Generated by Django 3.1.4 on 2021-05-31 10:30

from django.db import migrations, models
import django.db.models.deletion
import siperkap.models


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0010_auto_20210531_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='bantuan_kop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dak', models.CharField(blank=True, max_length=200, null=True)),
                ('kkp', models.CharField(blank=True, max_length=200, null=True)),
                ('tahun', models.IntegerField(default=siperkap.models.current_year, verbose_name='year')),
                ('koperasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siperkap.koperasi')),
            ],
        ),
    ]
