# Generated by Django 3.1.4 on 2021-06-07 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0011_bantuan_kop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bantuan_kop',
            name='tahun',
        ),
        migrations.AddField(
            model_name='bantuan_kop',
            name='apbd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bantuan_kop',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='bantuan_kub',
        ),
    ]
