# Generated by Django 3.1.4 on 2021-06-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0012_auto_20210607_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='bantuan_kub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dak', models.CharField(blank=True, max_length=200, null=True)),
                ('kkp', models.CharField(blank=True, max_length=200, null=True)),
                ('apbd', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('kub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siperkap.kub')),
            ],
        ),
    ]
