# Generated by Django 3.1.4 on 2021-06-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0013_bantuan_kub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bantuan_kop',
        ),
    ]
