# Generated by Django 3.1.4 on 2021-06-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0015_bantuan_kop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kub',
            name='alamat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kub',
            name='jumlah_anggota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kub',
            name='nama_ketua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kub',
            name='nama_kub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kub',
            name='no_registrasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kub',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
