# Generated by Django 3.1.4 on 2021-06-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0016_auto_20210608_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koperasi',
            name='alamat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='jumlah_anggota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='ketua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='nama_koperasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='no_hp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
