# Generated by Django 3.1.4 on 2021-06-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siperkap', '0017_auto_20210608_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bantuan_kop',
        ),
    ]
